apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-cluster
  region: eu-central-1

vpc:
  cidr: 10.0.0.0/16

nodeGroups: 
  - name: ng1-public
    instanceType: t3.small
    instanceName: ng1-instances
    availabilityZones: [eu-central-1c]
    desiredCapacity: 1 # Changing this will upscale or downscale nodes to the given number
    minSize: 1