apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: {{ .Values.Labels.postgresAppName }}
spec:
  type: NodePort
  ports:
   - port: 5432
     targetPort: 5432
  selector:
   app: {{ .Values.Labels.postgresAppName }}